### ISSUE TITLE
状态图描述的哪个对象？

### ISSUE THREAD

**Issue by pmlpml** [rookies-sysu/Dashboard#3]

**Comment by longjj** [comment]
@pmlpml 老师好，由于我之前画的时候对于状态图的理解还不够深入，现在会看好像将状态图的目标定在了宏观上整个系统了。（有错误）。

我尽快进行修改。然后作出进一步的回复，谢谢老师指出问题。

**Comment by longjj** [comment]
@pmlpml 老师好，两个小时之内有回复。

**Comment by jianjieluo** [comment]
@pmlpml 

已经修改好了，重新以领域模型图中的 Order 为对象构建状态图。

https://rookies-sysu.github.io/Dashboard/06-04-state-model
